### ISSUE TITLE
tmap?

### ISSUE THREAD

**Issue by DanOvando** [jafflerbach/spatial-analysis-R#1]
Hi guys! Quick question, what do we think about talking through [tmap](https://cran.r-project.org/web/packages/tmap/vignettes/tmap-nutshell.html) during this? I've started playing with it some and have been really impressed, but would be great to get your perspective given that you've had a lot more experience in spatial analysis and mapping

**Comment by jamiecmontgomery** [comment]
Hi @DanOvando! Great suggestion - this would actually give me an excuse to get to know tmap. I'll take a look at it and see if I can integrate it in the tutorial. If not, I'm happy to have you lead a little 'bonus' section for tmap if it's better that way.

**Comment by DanOvando** [comment]
I'm happy to help out, though I'm about 1 hour deep in tmap yet so not
exactly an expert ha.

Dan

On Tue, Apr 26, 2016 at 10:59 AM, Jamie Afflerbach <notifications@github.com

> wrote:
> 
> Hi @DanOvando https://github.com/DanOvando! Great suggestion - this
> would actually give me an excuse to get to know tmap. I'll take a look at
> it and see if I can integrate it in the tutorial. If not, I'm happy to have
> you lead a little 'bonus' section for tmap if it's better that way.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/jafflerbach/spatial-analysis-R/issues/1#issuecomment-214829575

## 

PhD Student, Project Researcher
Sustainable Fisheries Group
University of California, Santa Barbara

**Comment by bbest** [comment]
Here's more on tmap from http://remi-daigle.github.io/2016-04-15-UCSB/viz/#2_maps
