### ISSUE TITLE
tidy spatial: group_by() %>% summarize() works on sf

### ISSUE THREAD

**Issue by bbest** [jafflerbach/spatial-analysis-R#6]
Great job today @jafflerbach!

Here's a snippet for extending material to show off how sf objects can be used with dplyr functions to do aggregation steps for both spatial and attribute table:

```r
library(stringr)

west_shp_sf %>%
  mutate(
    state = ifelse(str_detect(rgn_key, 'CA'), 'CA', as.character(rgn_key))) %>%
  group_by(state) %>%
  summarize(
    area_km2 = sum(area_m2) / (1000*1000)) %>%
  plot()
```

![image](https://user-images.githubusercontent.com/2837257/31203478-0fb0f5fa-a91c-11e7-9ed0-4e183a56a7b7.png)

## References

* [Tidy spatial data in R: using dplyr, tidyr, and ggplot2 with sf](http://strimas.com/r/tidy-sf/#grouped-operations)
* [Spatial Data in R: New Directions at UseR2017](https://edzer.github.io/UseR2017/#higher-level-operations-summarise-interpolate-aggregate-st_join)
* [R Advanced Spatial Lessons](http://benbestphd.com/R-adv-spatial-lessons/tidy.html#regions-calculate-water) (source: [bbest/R-adv-spatial-lessons](https://github.com/bbest/R-adv-spatial-lessons)): material from data carpentry workshop at [Lawrence Berkeley National Lab: Sep 27-28, 2017](https://jsta.github.io/2017-09-27-LBNL/) using [bookdown](http://sbookdown.org/yihui/bookdown) with Software Carpentry css/jss.

**Comment by jamiecmontgomery** [comment]
I think we account for this now [here](http://jafflerbach.github.io/spatial-analysis-R/intro_to_sf.html#joins)
